ARG BUILDER_IMAGE=quay.io/kubevirt/builder:2606231619-4fe2cd536f

FROM --platform=linux/amd64 ${BUILDER_IMAGE} AS rpm-builder

ARG BUILD_ARCH=amd64
ARG CENTOS_STREAM_VERSION=9

WORKDIR /workspace
COPY libguestfs-tools_*_cs${CENTOS_STREAM_VERSION}.tar appliance_layer_*.tar rpm-tars/

RUN case ${BUILD_ARCH} in \
        amd64|x86_64) BAZEL_ARCH="x86_64" ;; \
        s390x|crossbuild-s390x) BAZEL_ARCH="s390x" ;; \
        *) echo "ERROR: libguestfs-tools not supported for ${BUILD_ARCH}"; exit 1 ;; \
    esac && \
    mkdir -p /rootfs /tmp/appliance && \
    tar -xf rpm-tars/libguestfs-tools_${BAZEL_ARCH}_cs${CENTOS_STREAM_VERSION}.tar -C /rootfs && \
    tar --no-same-owner -xf rpm-tars/appliance_layer_${BAZEL_ARCH}.tar -C /tmp/appliance/

RUN echo "nonroot-user:x:1001:1001:nonroot user:/home/nonroot-user:/sbin/nologin" > /rootfs/etc/passwd

FROM scratch

COPY --from=rpm-builder /rootfs/ /
COPY --from=rpm-builder /tmp/appliance/ /
